version: '3.1'

services:

  sticker_db:
    container_name: stickerDB
    image: postgres
    restart: unless-stopped
    ports:
      - 5432:5432
    volumes:
      - sticker_db_volume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  sticker_adminer:
    container_name: stickerAdminer
    image: adminer
    restart: always
    ports:
      - 8081:8080

volumes:
  sticker_db_volume:
